# -*- coding: utf-8 -*-
"""Projekt_pogoda_punkt_1_2_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/162X-WYAsfBVLC3DXf0eKEkBj4LiGFNUK

Wczytuje plik dane.csv jako tablice numpy
"""

import numpy as np
import matplotlib.pyplot as plt

data = np.loadtxt("/content/dane.csv", delimiter=',', dtype=str, encoding="cp1250")

"""# Zadanie 1

Sprawdzam ile jest linijek tekstu
"""

data.shape
print(data.shape[0])

"""Sprawdzam ile jest różnych stacji"""

id_stacji = data[:,0]
id_stacji = np.unique(id_stacji)
id_stacji.shape[0]

"""Sprawdzam ile jest wszystkich niepowtarzalnych dat"""

daty = data[:,2:5]
daty = np.unique(daty, axis = 0)
full_dates_number = daty.shape[0]
print(full_dates_number)

"""Tworzę tablicę składającą się z niepowtarzalnego {Id stacji, Nazwy stacji, Roku, Miesiąca i Dnia} \
Dla każdej stacji sprawdzam ile miała różnych dat
"""

stacje_z_data = data[:,0:5]
stacje_z_data = np.unique(stacje_z_data, axis = 0)

id_pomiary_dict = {id : stacje_z_data[stacje_z_data[:,0] == id].shape[0] for id in id_stacji}

"""Wyświetlam ilośc niepowtarzalnych dat pomiarów dla każdej stacji"""

list(id_pomiary_dict.items())

"""Wyliczam ile jest stacji które mają pełną historię pomiarów"""

id_pomiary = np.array(list(id_pomiary_dict.items()))
pelna_historia = id_pomiary[id_pomiary[:,1] == '8400']
pelna_historia.shape[0]

"""# Zadanie 2

Wybieram stację z pełną historią i wypisuje jej rok i miesiąc w których miała jakiś pomiar (skoro jest pełna to dla każdej daty go miała) (przyda się do wykresu)
"""

stacja_z_pelna_historia = '253170210'
dane_stacji_z_pelna_historia = stacje_z_data[stacje_z_data[:,0]==stacja_z_pelna_historia]

rok_miesiac = np.unique(dane_stacji_z_pelna_historia[:,2:4], axis = 0)
rok_miesiac

"""Wybieramy stacje z niepełą historią pomiarów.\
Następnie zostawiamy z tabilcy "stacje_z_data" tylko te których id (kod stacji)odpowiada wybranej stacji.\
Licze ile dni pomiarowych miała dana stacja dla danego miesiąca w danym roku, przebiegając po wszystkich latach i miesiącach.
"""

wybrana_stacja = '254180060'

dane_wybranej_stacji = stacje_z_data[stacje_z_data[:,0]==wybrana_stacja]

liczba_pomiarow = {
    (rok, miesiac) : dane_wybranej_stacji[(dane_wybranej_stacji[:,2] == rok) &
    (dane_wybranej_stacji[:,3] == miesiac)].shape[0]
    for (rok, miesiac) in rok_miesiac
    }
liczba_pomiarow

"""Rysuje wykres, i zmniejszam ilośc etykiet przy osi x ponieważ jest ich za dużo żeby je tak gęsto wyświetlic"""

y = list(liczba_pomiarow.values())
x = list(range(len(y)))

etykiety = [f"{rok}-{miesiac}" for (rok, miesiac) in liczba_pomiarow.keys()]

plt.title('Pomiary Wybranej Stacji W Danym Miesiącu')
plt.xlabel('Miesiąc i Rok')
plt.ylabel('Liczba pomiarów')
plt.bar(x, y)
krok = 48
plt.xticks(x[::krok], etykiety[::krok])
# plt.xticks(x, list(liczba_pomiarow.keys()))
plt.show()

"""# Zadanie 3

Wybieram potrzebne dane (aż do średniej temperatury) takie aby się nie powtarzały.\
Tworze słownik który liczy ilośc pomiarów.\
Wybieram stację z pełną historią i przechodze po (stacje_z_danymi) i wybieram jedynie te z podanym id kodem stacji.
"""

from datetime import datetime

stacje_z_danymi_2 = data[:,0:10]
stacje_z_danymi_2 = np.unique(stacje_z_danymi_2, axis = 0)

id_pomiary_dict_2 = {id : stacje_z_danymi_2[stacje_z_danymi_2[:,0] == id].shape[0] for id in id_stacji}

stacja_z_pelna_historia_2 = '249220180'
dane = stacje_z_danymi_2[stacje_z_danymi_2[:,0] == stacja_z_pelna_historia_2]
dane

"""Wybranie daty i temperatury"""

rok = dane[:,2].astype(int)
miesiac = dane[:,3].astype(int)
dzien = dane[:,4].astype(int)
temperatura = dane[:,9].astype(float)

"""Ustawiam początkową datę (2001.01.01)\
Następnie obliczam ile dni upłynęło od początkowej daty i zapisuje w tablicy numpy (dzięki temu każdemu pomiarowi mogę przypisac odpowiednią temperaturę)
"""

start = datetime(2001, 1, 1)

dni_od_startu = np.array([
    (datetime(r, m, d) - start).days
    for r, m, d in zip(rok, miesiac, dzien)
])

"""Rysuje wykres"""

plt.figure(figsize=(12, 5))
plt.plot(dni_od_startu, temperatura, linewidth=0.5)
plt.xlabel("Liczba dni od 01.01.2001")
plt.ylabel("Średnia dobowa temperatura [°C]")
plt.title("Średnia dobowa temperatura – stacja z pełną historią")
plt.grid(True)
plt.show()